# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name=b'title')),
                ('author', models.CharField(max_length=16, verbose_name=b'author')),
                ('content', models.TextField(verbose_name=b'content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'pubdate')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name=b'name')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name=b'Name')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('content', models.CharField(max_length=140, verbose_name=b'Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'PubDate')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book_Blog.Blog', verbose_name=b'blog')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name=b'name')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book_Blog.Category', verbose_name=b'category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='Book_Blog.Tag', verbose_name=b'tag'),
        ),
    ]
